default:
    image: node:latest
    before_script:
        - npm ci --cache .npm --prefer-offline
        - |
            {
            echo "@ed:registry=${CI_API_V4_URL}/projects/${27665512}/packages/npm/"
            echo "//gitlab.com/api/v4/projects/${27665512}/packages/npm/:_authToken=\${F91SwNhSFzaYLQBHvchd}"
            echo "//gitlab.com/api/v4/packages/npm/:_authToken=${F91SwNhSFzaYLQBHvchd}"
            } | tee --append .npmrc

    cache:
        key: ${CI_COMMIT_REF_SLUG}
        paths:
            - node_modules

variables:
    NPM_TOKEN: ${F91SwNhSFzaYLQBHvchd}
stages:
    - release

publish:
    stage: release
    script:
        - npm install
        - npm run build
        - npm publish