default:
    image: node:latest
    before_script:
        - npm ci --cache .npm --prefer-offline
        - |
            {
            echo "@experiencedigital:registry=${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/npm/"
            echo "//gitlab.com/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=\${CI_JOB_TOKEN}"
            echo "//gitlab.com/api/v4/packages/npm/:_authToken=${CI_JOB_TOKEN}"
            } | tee --append .npmrc

    cache:
        key: ${CI_COMMIT_REF_SLUG}
        paths:
            - node_modules

variables:
    NPM_TOKEN: ${CI_JOB_TOKEN}
stages:
    - release

publish:
    stage: release
    script:
        - npm install
        - npm run build
        - npm publish